'use client';
import * as React from "react";
import Head from 'next/head';

import { Inter } from "next/font/google";
import "./globals.css";

import { useState } from "react";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import IconButton from "@mui/material/IconButton";
import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";
import Avatar from "@mui/material/Avatar";
import Button from "@mui/material/Button";
import Tooltip from "@mui/material/Tooltip";
import Menu from "@mui/material/Menu";
import MenuItem from "@mui/material/MenuItem";
import AdbIcon from "@mui/icons-material/Adb";
import Link from "next/link";

// const pages = ["Tasks", "Log in"];
// const url = ["/tasks", "/navbar"];
// const pages = [
//   [ name: "Tasks", url: "/tasks" ],
//   [ name: "Log in", url: "/navbar" ],
//   // { name: "Sign up", url: "/signup" },
// ];
// const pages = [
//   ["Tasks", "/tasks"],
//   ["Log in", "/navbar"],
//   // ["Sign up", "/signup"],
// ];

const settings = ["Profile", "Account", "Dashboard", "Logout"];

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Cool Code",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const [anchorElNav, setAnchorElNav] = useState(null);
  const [anchorElUser, setAnchorElUser] = useState(null);

  const handleOpenNavMenu = (event) => {
    setAnchorElNav(event.currentTarget);
  };
  const handleOpenUserMenu = (event) => {
    setAnchorElUser(event.currentTarget);
  };

  const handleCloseNavMenu = () => {
    setAnchorElNav(null);
  };

  const handleCloseUserMenu = () => {
    setAnchorElUser(null);
  };

  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>

      <body className={inter.className}>
        <AppBar className="navBar" position="static">
          <Container maxWidth="xl">
            <Toolbar disableGutters>
              <AdbIcon sx={{ display: { xs: "none", md: "flex" }, mr: 1 }} />

              {/* Home */}
              <Typography
                variant="h4"
                noWrap
                component={Link}
                href="/"
                sx={{
                  mr: 2,
                  display: { xs: "none", md: "flex" },
                  fontFamily: "monospace",
                  fontWeight: 700,
                  letterSpacing: ".3rem",
                  color: "inherit",
                  textDecoration: "none",
                }}
              >
                CoolCode
              </Typography>
              
              <Typography
                variant="h6"
                noWrap
                component={Link}
                href="/login"
                sx={{
                  mr: 2,
                  display: { xs: "none", md: "flex" },
                  fontFamily: "Arial",
                  fontWeight: 700,
                  letterSpacing: ".3rem",
                  color: "inherit",
                  textDecoration: "none",
                }}
              >
                Login

              </Typography>

              <Typography
                variant="h6"
                noWrap
                component={Link}
                href="/signup"
                sx={{
                  mr: 2,
                  display: { xs: "none", md: "flex" },
                  fontFamily: "Arial",
                  fontWeight: 700,
                  letterSpacing: ".3rem",
                  color: "inherit",
                  textDecoration: "none",
                }}
              >
                Signup
              </Typography>


              {/* <Link href="/login">Login</Link>
              <Link href="/signup">Signup</Link> */}

              <Box sx={{ flexGrow: 0 }}>
                <Tooltip title="Open settings">
                  <IconButton onClick={handleOpenUserMenu} sx={{ p: 0 }}>
                    <Avatar
                      alt="Remy Sharp"
                      src="/static/images/avatar/2.jpg"
                    />
                  </IconButton>
                </Tooltip>
                <Menu
                  sx={{ mt: "45px" }}
                  id="menu-appbar"
                  anchorEl={anchorElUser}
                  anchorOrigin={{
                    vertical: "top",
                    horizontal: "right",
                  }}
                  keepMounted
                  transformOrigin={{
                    vertical: "top",
                    horizontal: "right",
                  }}
                  open={Boolean(anchorElUser)}
                  onClose={handleCloseUserMenu}
                >
                  {settings.map((setting) => (
                    <MenuItem key={setting} onClick={handleCloseUserMenu}>
                      <Typography textAlign="center">{setting}</Typography>
                    </MenuItem>
                  ))}
                </Menu>
              </Box>
            </Toolbar>
          </Container>
        </AppBar>

        <Button sx={{ marginTop: 1 }} variant="contained" className="backToHomeBtn">
          <Link href="/">← Back to home</Link>
        </Button>

        {children}
      </body>
    </html>
  );
}
